# Generated by Django 5.1.3 on 2024-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("artist", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("lyric", models.TextField()),
            ],
            options={"db_table": "lyrics", "managed": False,},
        ),
    ]
